export { InicioSection } from './InicioSection'
export { RecuerdosSection } from './RecuerdosSection'
export { MensajesSection } from './MensajesSection'
export { default as MusicaSection } from './MusicaSection'
export { RecetasSection } from './RecetasSection'
export { PlanesSection } from './PlanesSection'
export { default as FotosSection } from './FotosSection'
export { MascotasSection } from './MascotasSection'
export { ContentSection } from './ContentSection'
